//! # Mock University Oracle CLI
//!
//! A local development tool that simulates a University Oracle for Stream-Scholar.
//! Generates cryptographically valid ed25519-signed JSON payloads that the
//! Soroban contract's `report_student_gpa` function can verify.
//!
//! ## Usage
//!
//! ```bash
//! # Generate a new keypair (save the output – you'll need the public key in tests)
//! mock-oracle keygen
//!
//! # Sign a student GPA payload
//! mock-oracle sign \
//!   --secret-key <HEX_SECRET_KEY> \
//!   --student GABC...XYZ \
//!   --gpa 3.8 \
//!   --start-date 2024-09-01 \
//!   --status active
//! ```
//!
//! ## Security Note
//! Keys generated by this tool are intended for **testnet use only**.
//! Never use them on mainnet.

use clap::{Parser, Subcommand};
use ed25519_dalek::{Signer, SigningKey, VerifyingKey};
use rand::rngs::OsRng;
use serde::{Deserialize, Serialize};
use std::time::{SystemTime, UNIX_EPOCH};

// ── CLI definition ────────────────────────────────────────────────────────────

#[derive(Parser)]
#[command(
    name = "mock-oracle",
    about = "Stream-Scholar local mock University Oracle (testnet only)",
    version
)]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    /// Generate a new ed25519 keypair for testnet use.
    Keygen,

    /// Sign a student academic payload and output a JSON envelope.
    Sign {
        /// Hex-encoded 32-byte ed25519 secret key (from `keygen`).
        #[arg(long)]
        secret_key: String,

        /// Student Stellar address (G…).
        #[arg(long)]
        student: String,

        /// Student GPA as a decimal (e.g. 3.8). Stored as integer × 10.
        #[arg(long)]
        gpa: f64,

        /// Enrolment start date (YYYY-MM-DD).
        #[arg(long, default_value = "2024-09-01")]
        start_date: String,

        /// Academic status: `active`, `graduated`, or `suspended`.
        #[arg(long, default_value = "active")]
        status: String,
    },

    /// Verify a previously generated signed payload.
    Verify {
        /// Hex-encoded 32-byte ed25519 public key.
        #[arg(long)]
        public_key: String,

        /// JSON payload string (the `payload` field from `sign` output).
        #[arg(long)]
        payload: String,

        /// Hex-encoded 64-byte signature (the `signature` field from `sign` output).
        #[arg(long)]
        signature: String,
    },
}

// ── Data types ────────────────────────────────────────────────────────────────

/// The canonical academic payload that the oracle signs.
#[derive(Serialize, Deserialize, Debug)]
struct AcademicPayload {
    /// Stellar address of the student.
    student: String,
    /// GPA stored as integer × 10 (e.g. 38 for 3.8).
    gpa_scaled: u64,
    /// Human-readable GPA string.
    gpa_display: String,
    /// Enrolment start date.
    start_date: String,
    /// Academic status.
    status: String,
    /// Unix timestamp when this payload was generated.
    issued_at: u64,
    /// Network tag – always "testnet" for this tool.
    network: String,
}

/// The full signed envelope output by `sign`.
#[derive(Serialize, Debug)]
struct SignedEnvelope {
    /// Hex-encoded public key of the signing oracle.
    public_key: String,
    /// JSON-serialised `AcademicPayload` (the bytes that were signed).
    payload: String,
    /// Hex-encoded ed25519 signature over the UTF-8 bytes of `payload`.
    signature: String,
    /// Convenience field: the `gpa_scaled` value ready to pass to `report_student_gpa`.
    gpa_for_contract: u64,
}

// ── Helpers ───────────────────────────────────────────────────────────────────

fn now_unix() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .expect("system clock before epoch")
        .as_secs()
}

fn parse_secret_key(hex_str: &str) -> SigningKey {
    let bytes = hex::decode(hex_str).expect("secret key must be valid hex");
    let arr: [u8; 32] = bytes.try_into().expect("secret key must be exactly 32 bytes");
    SigningKey::from_bytes(&arr)
}

fn parse_public_key(hex_str: &str) -> VerifyingKey {
    let bytes = hex::decode(hex_str).expect("public key must be valid hex");
    let arr: [u8; 32] = bytes.try_into().expect("public key must be exactly 32 bytes");
    VerifyingKey::from_bytes(&arr).expect("invalid public key bytes")
}

// ── Command handlers ──────────────────────────────────────────────────────────

fn cmd_keygen() {
    let signing_key = SigningKey::generate(&mut OsRng);
    let verifying_key = signing_key.verifying_key();

    let output = serde_json::json!({
        "note": "TESTNET ONLY – never use on mainnet",
        "secret_key": hex::encode(signing_key.to_bytes()),
        "public_key": hex::encode(verifying_key.to_bytes()),
    });
    println!("{}", serde_json::to_string_pretty(&output).unwrap());
}

fn cmd_sign(secret_key: &str, student: &str, gpa: f64, start_date: &str, status: &str) {
    let signing_key = parse_secret_key(secret_key);
    let verifying_key = signing_key.verifying_key();

    // Scale GPA: 3.8 → 38, 4.0 → 40
    let gpa_scaled = (gpa * 10.0).round() as u64;

    let payload = AcademicPayload {
        student: student.to_string(),
        gpa_scaled,
        gpa_display: format!("{:.1}", gpa),
        start_date: start_date.to_string(),
        status: status.to_string(),
        issued_at: now_unix(),
        network: "testnet".to_string(),
    };

    let payload_json = serde_json::to_string(&payload).expect("serialisation failed");
    let signature = signing_key.sign(payload_json.as_bytes());

    let envelope = SignedEnvelope {
        public_key: hex::encode(verifying_key.to_bytes()),
        payload: payload_json,
        signature: hex::encode(signature.to_bytes()),
        gpa_for_contract: gpa_scaled,
    };

    println!("{}", serde_json::to_string_pretty(&envelope).unwrap());
}

fn cmd_verify(public_key: &str, payload: &str, signature: &str) {
    use ed25519_dalek::Verifier;

    let verifying_key = parse_public_key(public_key);
    let sig_bytes = hex::decode(signature).expect("signature must be valid hex");
    let sig_arr: [u8; 64] = sig_bytes.try_into().expect("signature must be 64 bytes");
    let sig = ed25519_dalek::Signature::from_bytes(&sig_arr);

    match verifying_key.verify(payload.as_bytes(), &sig) {
        Ok(()) => {
            let result = serde_json::json!({ "valid": true, "message": "Signature is valid." });
            println!("{}", serde_json::to_string_pretty(&result).unwrap());
        }
        Err(e) => {
            let result = serde_json::json!({ "valid": false, "message": format!("{}", e) });
            println!("{}", serde_json::to_string_pretty(&result).unwrap());
            std::process::exit(1);
        }
    }
}

// ── Entry point ───────────────────────────────────────────────────────────────

fn main() {
    let cli = Cli::parse();
    match cli.command {
        Commands::Keygen => cmd_keygen(),
        Commands::Sign { secret_key, student, gpa, start_date, status } => {
            cmd_sign(&secret_key, &student, gpa, &start_date, &status);
        }
        Commands::Verify { public_key, payload, signature } => {
            cmd_verify(&public_key, &payload, &signature);
        }
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use ed25519_dalek::{Signer, Verifier};

    fn test_keypair() -> (SigningKey, VerifyingKey) {
        let signing_key = SigningKey::generate(&mut OsRng);
        let verifying_key = signing_key.verifying_key();
        (signing_key, verifying_key)
    }

    #[test]
    fn test_keygen_produces_valid_keypair() {
        let (sk, vk) = test_keypair();
        // Round-trip through hex
        let sk_hex = hex::encode(sk.to_bytes());
        let vk_hex = hex::encode(vk.to_bytes());
        let sk2 = parse_secret_key(&sk_hex);
        let vk2 = parse_public_key(&vk_hex);
        assert_eq!(sk.to_bytes(), sk2.to_bytes());
        assert_eq!(vk.to_bytes(), vk2.to_bytes());
    }

    #[test]
    fn test_sign_produces_valid_signature() {
        let (sk, vk) = test_keypair();
        let payload = AcademicPayload {
            student: "GABC123".to_string(),
            gpa_scaled: 38,
            gpa_display: "3.8".to_string(),
            start_date: "2024-09-01".to_string(),
            status: "active".to_string(),
            issued_at: 1_700_000_000,
            network: "testnet".to_string(),
        };
        let payload_json = serde_json::to_string(&payload).unwrap();
        let sig = sk.sign(payload_json.as_bytes());
        // Verify with the matching public key
        assert!(vk.verify(payload_json.as_bytes(), &sig).is_ok());
    }

    #[test]
    fn test_tampered_payload_fails_verification() {
        let (sk, vk) = test_keypair();
        let payload_json = r#"{"student":"GABC","gpa_scaled":38}"#;
        let sig = sk.sign(payload_json.as_bytes());
        let tampered = r#"{"student":"GABC","gpa_scaled":40}"#;
        assert!(vk.verify(tampered.as_bytes(), &sig).is_err());
    }

    #[test]
    fn test_gpa_scaling() {
        // 3.8 → 38
        assert_eq!((3.8_f64 * 10.0).round() as u64, 38);
        // 4.0 → 40
        assert_eq!((4.0_f64 * 10.0).round() as u64, 40);
        // 3.5 → 35 (GPA bonus threshold in contract)
        assert_eq!((3.5_f64 * 10.0).round() as u64, 35);
    }

    #[test]
    fn test_wrong_key_fails_verification() {
        let (sk, _) = test_keypair();
        let (_, vk_other) = test_keypair();
        let payload_json = r#"{"student":"GABC","gpa_scaled":38}"#;
        let sig = sk.sign(payload_json.as_bytes());
        assert!(vk_other.verify(payload_json.as_bytes(), &sig).is_err());
    }
}
